package com.mingnong.xizangphone.dao.local;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.mingnong.xizangphone.dao.AnimalApplyBean;
import com.mingnong.xizangphone.dao.Animal_A;
import com.mingnong.xizangphone.dao.Animal_B;
import com.mingnong.xizangphone.dao.CacheTable;
import com.mingnong.xizangphone.dao.CodeXD;
import com.mingnong.xizangphone.dao.ProductApplyBean;
import com.mingnong.xizangphone.dao.Product_A;
import com.mingnong.xizangphone.dao.Product_B;
import com.mingnong.xizangphone.dao.ShenShiXianBean;
import com.mingnong.xizangphone.dao.StoreAnimalA;
import com.mingnong.xizangphone.dao.StoreAnimalB;
import com.mingnong.xizangphone.dao.StoreAnimApplyBean;
import com.mingnong.xizangphone.dao.StoreProductA;
import com.mingnong.xizangphone.dao.StoreProductApplyBean;
import com.mingnong.xizangphone.dao.StoreProductB;
import com.mingnong.xizangphone.dao.Unit;
import com.mingnong.xizangphone.dao.User;
import com.mingnong.xizangphone.dao.XiaoXiDaoBean;

import com.mingnong.xizangphone.dao.local.AnimalApplyBeanDao;
import com.mingnong.xizangphone.dao.local.Animal_ADao;
import com.mingnong.xizangphone.dao.local.Animal_BDao;
import com.mingnong.xizangphone.dao.local.CacheTableDao;
import com.mingnong.xizangphone.dao.local.CodeXDDao;
import com.mingnong.xizangphone.dao.local.ProductApplyBeanDao;
import com.mingnong.xizangphone.dao.local.Product_ADao;
import com.mingnong.xizangphone.dao.local.Product_BDao;
import com.mingnong.xizangphone.dao.local.ShenShiXianBeanDao;
import com.mingnong.xizangphone.dao.local.StoreAnimalADao;
import com.mingnong.xizangphone.dao.local.StoreAnimalBDao;
import com.mingnong.xizangphone.dao.local.StoreAnimApplyBeanDao;
import com.mingnong.xizangphone.dao.local.StoreProductADao;
import com.mingnong.xizangphone.dao.local.StoreProductApplyBeanDao;
import com.mingnong.xizangphone.dao.local.StoreProductBDao;
import com.mingnong.xizangphone.dao.local.UnitDao;
import com.mingnong.xizangphone.dao.local.UserDao;
import com.mingnong.xizangphone.dao.local.XiaoXiDaoBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig animalApplyBeanDaoConfig;
    private final DaoConfig animal_ADaoConfig;
    private final DaoConfig animal_BDaoConfig;
    private final DaoConfig cacheTableDaoConfig;
    private final DaoConfig codeXDDaoConfig;
    private final DaoConfig productApplyBeanDaoConfig;
    private final DaoConfig product_ADaoConfig;
    private final DaoConfig product_BDaoConfig;
    private final DaoConfig shenShiXianBeanDaoConfig;
    private final DaoConfig storeAnimalADaoConfig;
    private final DaoConfig storeAnimalBDaoConfig;
    private final DaoConfig storeAnimApplyBeanDaoConfig;
    private final DaoConfig storeProductADaoConfig;
    private final DaoConfig storeProductApplyBeanDaoConfig;
    private final DaoConfig storeProductBDaoConfig;
    private final DaoConfig unitDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig xiaoXiDaoBeanDaoConfig;

    private final AnimalApplyBeanDao animalApplyBeanDao;
    private final Animal_ADao animal_ADao;
    private final Animal_BDao animal_BDao;
    private final CacheTableDao cacheTableDao;
    private final CodeXDDao codeXDDao;
    private final ProductApplyBeanDao productApplyBeanDao;
    private final Product_ADao product_ADao;
    private final Product_BDao product_BDao;
    private final ShenShiXianBeanDao shenShiXianBeanDao;
    private final StoreAnimalADao storeAnimalADao;
    private final StoreAnimalBDao storeAnimalBDao;
    private final StoreAnimApplyBeanDao storeAnimApplyBeanDao;
    private final StoreProductADao storeProductADao;
    private final StoreProductApplyBeanDao storeProductApplyBeanDao;
    private final StoreProductBDao storeProductBDao;
    private final UnitDao unitDao;
    private final UserDao userDao;
    private final XiaoXiDaoBeanDao xiaoXiDaoBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        animalApplyBeanDaoConfig = daoConfigMap.get(AnimalApplyBeanDao.class).clone();
        animalApplyBeanDaoConfig.initIdentityScope(type);

        animal_ADaoConfig = daoConfigMap.get(Animal_ADao.class).clone();
        animal_ADaoConfig.initIdentityScope(type);

        animal_BDaoConfig = daoConfigMap.get(Animal_BDao.class).clone();
        animal_BDaoConfig.initIdentityScope(type);

        cacheTableDaoConfig = daoConfigMap.get(CacheTableDao.class).clone();
        cacheTableDaoConfig.initIdentityScope(type);

        codeXDDaoConfig = daoConfigMap.get(CodeXDDao.class).clone();
        codeXDDaoConfig.initIdentityScope(type);

        productApplyBeanDaoConfig = daoConfigMap.get(ProductApplyBeanDao.class).clone();
        productApplyBeanDaoConfig.initIdentityScope(type);

        product_ADaoConfig = daoConfigMap.get(Product_ADao.class).clone();
        product_ADaoConfig.initIdentityScope(type);

        product_BDaoConfig = daoConfigMap.get(Product_BDao.class).clone();
        product_BDaoConfig.initIdentityScope(type);

        shenShiXianBeanDaoConfig = daoConfigMap.get(ShenShiXianBeanDao.class).clone();
        shenShiXianBeanDaoConfig.initIdentityScope(type);

        storeAnimalADaoConfig = daoConfigMap.get(StoreAnimalADao.class).clone();
        storeAnimalADaoConfig.initIdentityScope(type);

        storeAnimalBDaoConfig = daoConfigMap.get(StoreAnimalBDao.class).clone();
        storeAnimalBDaoConfig.initIdentityScope(type);

        storeAnimApplyBeanDaoConfig = daoConfigMap.get(StoreAnimApplyBeanDao.class).clone();
        storeAnimApplyBeanDaoConfig.initIdentityScope(type);

        storeProductADaoConfig = daoConfigMap.get(StoreProductADao.class).clone();
        storeProductADaoConfig.initIdentityScope(type);

        storeProductApplyBeanDaoConfig = daoConfigMap.get(StoreProductApplyBeanDao.class).clone();
        storeProductApplyBeanDaoConfig.initIdentityScope(type);

        storeProductBDaoConfig = daoConfigMap.get(StoreProductBDao.class).clone();
        storeProductBDaoConfig.initIdentityScope(type);

        unitDaoConfig = daoConfigMap.get(UnitDao.class).clone();
        unitDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        xiaoXiDaoBeanDaoConfig = daoConfigMap.get(XiaoXiDaoBeanDao.class).clone();
        xiaoXiDaoBeanDaoConfig.initIdentityScope(type);

        animalApplyBeanDao = new AnimalApplyBeanDao(animalApplyBeanDaoConfig, this);
        animal_ADao = new Animal_ADao(animal_ADaoConfig, this);
        animal_BDao = new Animal_BDao(animal_BDaoConfig, this);
        cacheTableDao = new CacheTableDao(cacheTableDaoConfig, this);
        codeXDDao = new CodeXDDao(codeXDDaoConfig, this);
        productApplyBeanDao = new ProductApplyBeanDao(productApplyBeanDaoConfig, this);
        product_ADao = new Product_ADao(product_ADaoConfig, this);
        product_BDao = new Product_BDao(product_BDaoConfig, this);
        shenShiXianBeanDao = new ShenShiXianBeanDao(shenShiXianBeanDaoConfig, this);
        storeAnimalADao = new StoreAnimalADao(storeAnimalADaoConfig, this);
        storeAnimalBDao = new StoreAnimalBDao(storeAnimalBDaoConfig, this);
        storeAnimApplyBeanDao = new StoreAnimApplyBeanDao(storeAnimApplyBeanDaoConfig, this);
        storeProductADao = new StoreProductADao(storeProductADaoConfig, this);
        storeProductApplyBeanDao = new StoreProductApplyBeanDao(storeProductApplyBeanDaoConfig, this);
        storeProductBDao = new StoreProductBDao(storeProductBDaoConfig, this);
        unitDao = new UnitDao(unitDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        xiaoXiDaoBeanDao = new XiaoXiDaoBeanDao(xiaoXiDaoBeanDaoConfig, this);

        registerDao(AnimalApplyBean.class, animalApplyBeanDao);
        registerDao(Animal_A.class, animal_ADao);
        registerDao(Animal_B.class, animal_BDao);
        registerDao(CacheTable.class, cacheTableDao);
        registerDao(CodeXD.class, codeXDDao);
        registerDao(ProductApplyBean.class, productApplyBeanDao);
        registerDao(Product_A.class, product_ADao);
        registerDao(Product_B.class, product_BDao);
        registerDao(ShenShiXianBean.class, shenShiXianBeanDao);
        registerDao(StoreAnimalA.class, storeAnimalADao);
        registerDao(StoreAnimalB.class, storeAnimalBDao);
        registerDao(StoreAnimApplyBean.class, storeAnimApplyBeanDao);
        registerDao(StoreProductA.class, storeProductADao);
        registerDao(StoreProductApplyBean.class, storeProductApplyBeanDao);
        registerDao(StoreProductB.class, storeProductBDao);
        registerDao(Unit.class, unitDao);
        registerDao(User.class, userDao);
        registerDao(XiaoXiDaoBean.class, xiaoXiDaoBeanDao);
    }
    
    public void clear() {
        animalApplyBeanDaoConfig.clearIdentityScope();
        animal_ADaoConfig.clearIdentityScope();
        animal_BDaoConfig.clearIdentityScope();
        cacheTableDaoConfig.clearIdentityScope();
        codeXDDaoConfig.clearIdentityScope();
        productApplyBeanDaoConfig.clearIdentityScope();
        product_ADaoConfig.clearIdentityScope();
        product_BDaoConfig.clearIdentityScope();
        shenShiXianBeanDaoConfig.clearIdentityScope();
        storeAnimalADaoConfig.clearIdentityScope();
        storeAnimalBDaoConfig.clearIdentityScope();
        storeAnimApplyBeanDaoConfig.clearIdentityScope();
        storeProductADaoConfig.clearIdentityScope();
        storeProductApplyBeanDaoConfig.clearIdentityScope();
        storeProductBDaoConfig.clearIdentityScope();
        unitDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        xiaoXiDaoBeanDaoConfig.clearIdentityScope();
    }

    public AnimalApplyBeanDao getAnimalApplyBeanDao() {
        return animalApplyBeanDao;
    }

    public Animal_ADao getAnimal_ADao() {
        return animal_ADao;
    }

    public Animal_BDao getAnimal_BDao() {
        return animal_BDao;
    }

    public CacheTableDao getCacheTableDao() {
        return cacheTableDao;
    }

    public CodeXDDao getCodeXDDao() {
        return codeXDDao;
    }

    public ProductApplyBeanDao getProductApplyBeanDao() {
        return productApplyBeanDao;
    }

    public Product_ADao getProduct_ADao() {
        return product_ADao;
    }

    public Product_BDao getProduct_BDao() {
        return product_BDao;
    }

    public ShenShiXianBeanDao getShenShiXianBeanDao() {
        return shenShiXianBeanDao;
    }

    public StoreAnimalADao getStoreAnimalADao() {
        return storeAnimalADao;
    }

    public StoreAnimalBDao getStoreAnimalBDao() {
        return storeAnimalBDao;
    }

    public StoreAnimApplyBeanDao getStoreAnimApplyBeanDao() {
        return storeAnimApplyBeanDao;
    }

    public StoreProductADao getStoreProductADao() {
        return storeProductADao;
    }

    public StoreProductApplyBeanDao getStoreProductApplyBeanDao() {
        return storeProductApplyBeanDao;
    }

    public StoreProductBDao getStoreProductBDao() {
        return storeProductBDao;
    }

    public UnitDao getUnitDao() {
        return unitDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public XiaoXiDaoBeanDao getXiaoXiDaoBeanDao() {
        return xiaoXiDaoBeanDao;
    }

}
